### ISSUE TITLE
error while creating the Flourescence processor

### ISSUE THREAD

**Issue by DavidMF123** [gcharvin/DetecDiv#10]
i got this error message just when creating the processor and selecting the Processing and computeFluo options on the drop down menus:

this is a shallow object
Dot indexing is not supported for variables of this type.

Error in listAvailableChannels (line 12)
    classifiers={proj.processing.classification.strid};

Error in computeFluo (line 3)
 listChannels=listAvailableChannels;

Error in processGUI/displayParam (line 62)
                param=feval(classiObj.processFun);

Error in processGUI/startupFcn (line 129)
            displayParam(app)

Error in processGUI>@(app)startupFcn(app,varargin{:}) (line 300)
            runStartupFcn(app, @(app)startupFcn(app, varargin{:}))

Error in appdesigner.internal.service.AppManagementService/runStartupFcn (line 103)
            startupFcn(app);

Error in matlab.apps.AppBase/runStartupFcn (line 69)
            ams.runStartupFcn(app, startfcn);

Error in processGUI (line 300)
            runStartupFcn(app, @(app)startupFcn(app, varargin{:}))

Error in detecdiv/displayNodes/contextMenuProcessFcn (line 243)
                processGUI(clas)
 
Error using matlab.ui.internal.controller.WebMenuController/fireActionEvent
Error while evaluating Menu Callback.

i did it with the latest code update (from 2 days ago) and with a 3 channel experiment that already has been segmented and classified regarding cell cycle stages. maybe i'm missing another matlab package?
thanks

**Comment by gcharvin** [comment]
Hi David, I will look into it and get back to you ASAP. Gilles

**Comment by gcharvin** [comment]
Let me know if you stil experience this error. I just tried on my side and saw no problem. It might have been corrected since July.

**Comment by DavidMF123** [comment]
yeah it was

El dj., 8 de des. 2022, 16:41, Gilles Charvin ***@***.***> va
escriure:

**Comment by gcharvin** [comment]
ok I will close this thread then .
